# Generated by Django 4.0.5 on 2022-06-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_apps', '0002_tag_project_vote_total_project_vote_ratio_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titile',
            new_name='title',
        ),
    ]
