# Generated by Django 4.0.5 on 2022-06-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_apps', '0003_rename_titile_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vote_Total',
            new_name='vote_total',
        ),
    ]
