# Generated by Django 4.0.5 on 2022-06-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_apps', '0007_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
